### ISSUE TITLE
Add MariaDB with RDS

### ISSUE THREAD

**Issue by chanwookpark** [spring-cloud/spring-cloud-aws#105]
AWS is now MariaDB with RDS.
So I test with Spring Data(1.1.0.BUILD-SNAPSHOT), not yet support for that.
Of course, some later add this case, but I request to a little help.

Thanks. 

Trace is below: 

```
Caused by: java.lang.IllegalStateException: No database type found for engine:'mariadb'
	at org.springframework.cloud.aws.jdbc.datasource.support.DatabaseType.fromEngine(DatabaseType.java:44)
	at org.springframework.cloud.aws.jdbc.rds.AmazonRdsDataSourceFactoryBean.fromRdsInstance(AmazonRdsDataSourceFactoryBean.java:183)
	at org.springframework.cloud.aws.jdbc.rds.AmazonRdsDataSourceFactoryBean.createDataSourceInstance(AmazonRdsDataSourceFactoryBean.java:152)
	at org.springframework.cloud.aws.jdbc.rds.AmazonRdsDataSourceFactoryBean.createInstance(AmazonRdsDataSourceFactoryBean.java:129)
	at org.springframework.cloud.aws.jdbc.rds.AmazonRdsDataSourceFactoryBean.createInstance(AmazonRdsDataSourceFactoryBean.java:45)
	at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:134)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 213 more
```

**Comment by aemruli** [comment]
Hi @chanwookpark we currently do not have support for MariaDB, but will add for the next release (end of month). For time being you have to configure the database on yourself (fetching the DB info and creating a data source)

**Comment by chanwookpark** [comment]
Hi @aemruli . 
I expect to add feature.

thanks.

**Comment by aemruli** [comment]
@chanwookpark I have added support for MariaDB and Aurora. You should just add the driver to your class path, after that you can use the MaridaDB @ RDS

**Comment by chanwookpark** [comment]
@aemruli thanks your support! 
I will try for that.
