### ISSUE TITLE
Issues with SSL

### ISSUE THREAD

**Issue by rogeriobiondi** [spring-cloud/spring-cloud-aws#106]
Hello,

I'm trying running a spring.boot application using spring-cloud-aws and getting the following error:

2015-10-13 16:20:57.390  INFO 5308 --- [           main] com.amazonaws.http.AmazonHttpClient      : Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException:
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderExce
ption: unable to find valid certification path to requested target
       at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
       at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
       at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
       at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)

Is possible configuring the spring-cloud-aws app to make the api calls with sslEnabled=false?

Thank you very much.

**Comment by rogeriobiondi** [comment]
Any other adjustment or workaround possible? Thanks

**Comment by aemruli** [comment]
Hi @rogeriobiondi you can set the protocol with an explicit ClientConfiguration. It is currently not possible to configure a client configuration, but you can setup yours. See https://github.com/spring-cloud/spring-cloud-aws/issues/63

In general I would question if you really want to use http instead of https, because the latter is the (sensible) default.

**Comment by noelob** [comment]
@rogeriobiondi what version of Java are you using? 1.6? I've seen the same issue recently. It appears the most AWS services are been given new SSL certs and the default truststore in JDK 1.6 is too old to recognize that they're valid. Upgrading to JDK 7 or 8 will fix this

**Comment by rogeriobiondi** [comment]
Hello, thank you very much for your help. We are using java 1.8.0_60

**Comment by aemruli** [comment]
Hello @rogeriobiondi could you solve this issue ? Otherwise I am going to close this ticket as #63 covers the possibility to specificy http as the protocol.
