### ISSUE TITLE
Can't confirm SNS subscription

### ISSUE THREAD

**Issue by akirasosa** [spring-cloud/spring-cloud-aws#138]
I have got an error when received a request from SNS.

```
ava.lang.IllegalArgumentException: Invoked method public abstract void org.springframework.cloud.aws.messaging.endpoint.NotificationStatus.confirmSubscription() is no accessor method!
        at org.springframework.util.Assert.notNull(Assert.java:115)
        at org.springframework.data.projection.MapAccessingMethodInterceptor$Accessor.<init>(MapAccessingMethodInterceptor.java:97)
        at org.springframework.data.projection.MapAccessingMethodInterceptor.invoke(MapAccessingMethodInterceptor.java:62)
        at org.springframework.data.projection.ProjectingMethodInterceptor.invoke(ProjectingMethodInterceptor.java:75)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.projection.ProxyProjectionFactory$TargetAwareMethodInterceptor.invoke(ProxyProjectionFactory.java:214)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
        at com.sun.proxy.$Proxy123.confirmSubscription(Unknown Source)
```

```java
@RestController
@RequestMapping("/sns/xxx")
public class SNSTestController {
    @NotificationSubscriptionMapping
    public void handleSubscriptionMessage(NotificationStatus status) throws IOException {
        status.confirmSubscription();
    }
}
```

```java
@Configuration
@ComponentScan
@EnableAutoConfiguration(exclude = ElastiCacheAutoConfiguration.class)
public class Application extends SpringBootServletInitializer {

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(Application.class);
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```

```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-aws-messaging</artifactId>
            <version>1.0.4.RELEASE</version>
        </dependency>
```

**Comment by irshad-qb** [comment]
Seems like you missed the resolver. 
Please add it like here in this tutorial [link](http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_annotation_driven_http_notification_endpoint).

**Comment by aemruli** [comment]
@akirasosa closing for now as the link should help. Otherwise please re-open the issue

**Comment by forbode** [comment]
I will leave this here for others:

1) I was using Spring Data Rest with no UI
2) I am not using autoconfigure due to limitations it places

First I tried registering custom resolvers in my RepositoryRestConfigurerAdapter, which does not work when SNS tries to verify the subscription. 

After digging a bit I used the [source from Spring Cloud AWS](https://github.com/spring-cloud/spring-cloud-aws/blob/147420f4d86806b921d4d7533813d11d73692fb5/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/config/annotation/SnsWebConfiguration.java) to add the resolvers. 

This worked just fine.

**Comment by alexsaleh** [comment]
Hi @forbode, 

I'm not able to receive messages using the same configuration (in Spring boot, so the xml resolver config does not help). What do I need to add in my config to add the resolvers ? It's not clear to me.
Thanks!
Alex

**Comment by aemruli** [comment]
Hi @akirasosa did you register a subscription ? Does the url match to the URL of your controller ? 
You can turn on request logging on the spring mvc classes to see if a request arrives at all.

**Comment by karunakerreddyv** [comment]
Publishing to HTTP/HTTPs Endpoints Using SNS and the AWS SDK for Java (This worked for me)
https://aws.amazon.com/blogs/developer/publishing-to-https-endpoints-using-sns-and-the-aws-sdk-for-java/

**Comment by gpmind** [comment]
The SNS integration doesn't work for me at all. Configurations on resolvers or not.
