### ISSUE TITLE
@SQSListener: 413 Error after few hours of execution

### ISSUE THREAD

**Issue by cd-rnukala** [spring-cloud/spring-cloud-aws#156]
**Problem**: We have SQSListener polling on a certain queue and it executes fine on all our test environments. But on Produciton when we deploy it executes fine for few hours and after that we see the below error happening. Any help is appreciated. Jar i am using is **spring-cloud-aws-messaging-1.1.0RC2.jar**

**Error Log:**
26 May 2016 14:23:25,641 [simpleMessageListenerContainer-1,WARN ,SimpleMessageListenerContainer] An Exception occurred while polling queue '${queuename}'. The failing operation will be retried in 10000 milliseconds
com.amazonaws.AmazonServiceException: Unable to unmarshall error response (HTTP content length exceeded 1662976 bytes.) (Service: AmazonSQS; Status Code: 413; Error Code: 413 Request Entity Too Large; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:803)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2419)
	at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1130)
	at com.amazonaws.services.sqs.AmazonSQSAsyncClient$23.call(AmazonSQSAsyncClient.java:1678)
	at com.amazonaws.services.sqs.AmazonSQSAsyncClient$23.call(AmazonSQSAsyncClient.java:1676)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.null(Unknown Source)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:125)
	at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:132)
	at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:80)
	at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:40)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1187)

**Comment by nsmolenskii** [comment]
most probably same reasons as #111

**Comment by alainsahli** [comment]
See #111
