### ISSUE TITLE
An Exception occurred while polling queue

### ISSUE THREAD

**Issue by kolmar1991** [spring-cloud/spring-cloud-aws#161]
Hi,
I have created sqs listener method as following:
```
 @MessageMapping("QueueName")
    public void handleMessage(String message) throws IOException, InvalidFormatException {
}
```
Everything works fine locally. When I deploy it on Elastic Beanstalk on Tomcat I'm getting following error:

```
WARN 22429 --- [enerContainer-1] s.c.a.m.l.SimpleMessageListenerContainer : An Exception occurred while polling queue 'QueueName'. The failing operation will be retried in 10000 milliseconds

java.lang.NullPointerException: null
	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$AsynchronousMessageListener.run(SimpleMessageListenerContainer.java:255) ~[spring-cloud-aws-messaging-1.1.0.RELEASE.jar:1.1.0.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

This is my confguration:
```
    @Bean
    public AmazonSQS amazonSQS() {
        AmazonSQS amazonSQS = new AmazonSQSAsyncClient(new DefaultAWSCredentialsProviderChain());
        Region region = Regions.getCurrentRegion();
        if (region == null) {
            region = Region.getRegion(Regions.EU_CENTRAL_1);
        }
        amazonSQS.setRegion(region);
        return amazonSQS;
    }
```

I have no idea what is wrong. Could you advise?

**Comment by artembilan** [comment]
Don't you have in logs before something like this:
```
try {
	destinationUrl = getDestinationResolver().resolveDestination(queue);
} catch (DestinationResolutionException e) {
	getLogger().warn(String.format("The queue with name '%s' does not exist.", queue), e);
	return null;
}
```
?
Having that we place `null` into the `this.registeredQueues` `Map`. 
Therefore `AsynchronousMessageListener` accepts `null` for `queueAttributes` in the end.
And we have `NPE` evaluating this:
```
ReceiveMessageResult receiveMessageResult = getAmazonSqs().receiveMessage(this.queueAttributes.getReceiveMessageRequest());
```
Because `this.queueAttributes` is `null` there.

Does it make sense for you ?

**Comment by kolmar1991** [comment]
Thanks. It works now. Previously I had problems with S3 access. I granted EC2

**Comment by artembilan** [comment]
Glad to be helpful.
I consider the issue as resolved.
Closing.
