### ISSUE TITLE
SQS failing to poll messages when deployed to AWS/EC2 environment

### ISSUE THREAD

**Issue by Adam-Bronfin** [spring-cloud/spring-cloud-aws#189]
Spring boot app works fine running locally connecting to sandbox S3 & sandbox SQS, using DefaultAWSCredentialsProviderChain and set as system property.

When application is deployed to EC2 environment and using ProfileCredentials, I get a continuous stream of following error in CloudWatch:

```
{
    "Host": "e73776616f27",
    "Date": "2016-12-20T21:52:56,777",
    "Thread": "simpleMessageListenerContainer-1",
    "Level": "WARN ",
    "Logger": "org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer",
    "Msg": "An Exception occurred while polling queue 'my-queue-name'. The failing operation will be retried in 10000 milliseconds",
    "Identifiers": {
        "Jvm-Instance": "",
        "App-Name": "keyring-selfie-service",
        "Correlation-Id": "ca9a556e-2fbc-4e49-8fb8-0e921ebb79bc",
        "Session-Id": "",
        "Thread-Group": "main",
        "Thread-Id": "32",
        "Version": ""
    }
}
java.lang.NullPointerException
at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$AsynchronousMessageListener.run(SimpleMessageListenerContainer.java:255) [spring-cloud-aws-messaging-1.1.1.RELEASE.jar:1.1.1.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
```

The problem boils down to SimpleMessageListenerContainer.java:255 : 

ReceiveMessageResult receiveMessageResult = getAmazonSqs().receiveMessage(this.queueAttributes.getReceiveMessageRequest());

`this.queueAttributes` is null.

I have tried everything, including @EnableContextCredentials(instanceProfile=true), to setting cloud.aws.credentials.instanceProfile=true while making sure access & secretKey is null.

Please assist.

**Comment by artembilan** [comment]
What I can say you `NPE` comes from here:
```
try {
	destinationUrl = getDestinationResolver().resolveDestination(queue);
} catch (DestinationResolutionException e) {
	getLogger().warn(String.format("The queue with name '%s' does not exist.", queue), e);
	return null;
}
```
So, be sure that you really have that queue on AWS and it is available for your user.

OTOH I agree that such a situation should be handled some how other way not lead to the `NPE`...

**Comment by Adam-Bronfin** [comment]
What file is:

destinationUrl = getDestinationResolver().resolveDestination

in?

**Comment by Adam-Bronfin** [comment]
By the way I'm using 1.1.1.RELEASE

**Comment by Adam-Bronfin** [comment]
I have confirmed that the queue it's using does exist on AWS

**Comment by artembilan** [comment]
`AbstractMessageListenerContainer.queueAttributes()` which is called from the `AbstractMessageListenerContainer.afterPropertiesSet()`.

Be sure that you use proper `ResourceIdResolver` there.

>  I'm using 1.1.1.RELEASE

Either do I

**Comment by Adam-Bronfin** [comment]
What should the proper ResourceIdResolver be?

Can you tell based on what I've listed above whether I'm missing any needed configuration or annotations?

**Comment by Adam-Bronfin** [comment]
On start up locally I hit the breakpoint of .resolveDestination(queueName) with a different queue it shouldn't have access to and threw:

Caused by: com.amazonaws.services.sqs.model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. (Service: AmazonSQS; Status Code: 400; Error Code: AWS.SimpleQueueService.NonExistentQueue; Request ID: f179100d-d0fa-5340........)

So I don't think this is the issue.

**Comment by artembilan** [comment]
Well, otherwise it isn't clear to me how `this.queueAttributes` can be `null` yet...
If you can drop break point there, so why just don't follow with the whole process from the `AbstractMessageListenerContainer.afterPropertiesSet()` ?

**Comment by Adam-Bronfin** [comment]
I have followed through these breakpoints but I can't do this on the EC2 instance, which is where the problem is occurring.

Can you confirm based on my above  code that I haven't missed any configuration steps?

**Comment by artembilan** [comment]
Sorry, I can't confirm anything.
Have never tried SQS on EC2.

Just try to share some thoughts with a hope to shed the light.

**Comment by Adam-Bronfin** [comment]
Well we tried using aws cli on EC2 instance and all of the profile credentials and meta data is available correctly

**Comment by lafod** [comment]
@Adam-Bronfin I was able to get this working by editing the SQS queue permission.

**Comment by djmrr** [comment]
@Adam-Bronfin 
This is what I have and it works... pretty much don't know it it's much help at all :/ :
```@Configuration
public class SpringCloudSQSConfig {

    @Bean
    public AmazonSQSAsync amazonSQS(@Value("us-west-2") String awsRegion) {
        System.out.println("\nBuilding amazonSQS bean...\n");
        AmazonSQSAsync theAsyncSqs = null;
        try {
            theAsyncSqs = AmazonSQSAsyncClientBuilder.standard()
                    .withRegion(awsRegion)
                    .withCredentials(new EC2ContainerCredentialsProviderWrapper())
//                    .withCredentials(new DefaultAWSCredentialsProviderChain())
                    .build();
        } catch (Exception ex) {
            System.out.println("Error: \n" + ex.toString() + "\n" + ex.getStackTrace() + "\n");
        }
        return theAsyncSqs;
    }

    @Bean
    public SimpleMessageListenerContainerFactory simpleMessageListenerContainerFactory(AmazonSQSAsync amazonSqs) {
        SimpleMessageListenerContainerFactory factory = new SimpleMessageListenerContainerFactory();
        factory.setAmazonSqs(amazonSqs);
        factory.setMaxNumberOfMessages(5);
        return factory;
    }

    @Bean
    public QueueMessageHandler queueMessageHandler(AmazonSQSAsync amazonSQSAsync) {
        QueueMessageHandlerFactory factory = new QueueMessageHandlerFactory();
        factory.setAmazonSqs(amazonSQSAsync);
        return factory.createQueueMessageHandler();
    }

    @Bean
    public SimpleMessageListenerContainer simpleMessageListenerContainer(
            SimpleMessageListenerContainerFactory simpleMessageListenerContainerFactory,
            QueueMessageHandler queueMessageHandler) {
        SimpleMessageListenerContainer container = simpleMessageListenerContainerFactory.createSimpleMessageListenerContainer();
        container.setMessageHandler(queueMessageHandler);
        // I think the setWaitTimeOut is supeeer important...I think...idk
        container.setWaitTimeOut(20);
        return container;
    }

}

// And then the service that listens/writes:


@Service
public class SpringCloudSQSService {
    @Autowired
    AmazonSQSAsync amazonSQSAsync;

    private Logger sqsServiceLogger;

    private QueueMessagingTemplate queueMessagingTemplate;

    @Autowired
    public void SpringCloudSQSService(AmazonSQSAsync amazonSQSAsync) {
        this.queueMessagingTemplate = new QueueMessagingTemplate(amazonSQSAsync);
        this.sqsServiceLogger = Logger.getLogger("SpringCloudSQSService");
    }

    @MessageMapping("your.fifo")
    @SqsListener(value = "your.fifo", deletionPolicy = SqsMessageDeletionPolicy.NEVER)
    public void receiveMessage(String message, @Headers Map<String, String> headers, Acknowledgment ack) {
// manually ack'ing messages
        this.sqsServiceLogger.log(new LogRecord(Level.INFO, "Receive Message Called!"));
        this.sqsServiceLogger.log(new LogRecord(Level.INFO, "This is the message received: " + message));
        for (String key : headers.keySet()) {
            this.sqsServiceLogger.log(new LogRecord(Level.INFO, "This is the header-key: " + key));
            if (key.equals("Acknowledgment")) {
                this.sqsServiceLogger.log(new LogRecord(Level.INFO, "Acknowledgement key/value exists :)"));
            } else {
                this.sqsServiceLogger.log(new LogRecord(Level.INFO, " key: " + key + " value: " + headers.get(key)));
            }
        }
        this.sqsServiceLogger.log(new LogRecord(Level.INFO, "-> Acknowledging ahead :) "));
        ack.acknowledge();
    }

    public void send(String topicName, String message) throws Exception {
        this.sqsServiceLogger.log(new LogRecord(Level.INFO, "This is topicName " + topicName));
        this.sqsServiceLogger.log(new LogRecord(Level.INFO, "This is message " + message));
        Message msg = MessageBuilder
                .withPayload(message)
                .setHeader(SqsMessageHeaders.SQS_GROUP_ID_HEADER, "test")
                .setHeader(SqsMessageHeaders.SQS_DEDUPLICATION_ID_HEADER, UUID.randomUUID().toString())
                .build();
        try {
            this.sqsServiceLogger.log(new LogRecord(Level.INFO, "Sending the message to queuemessagingetemplate"));
            this.queueMessagingTemplate.send(topicName, msg);
        } catch (MessagingException ex) {
            this.sqsServiceLogger.log(new LogRecord(Level.WARNING, "ERROR: -> " + ex.toString()));
            throw new Exception("Error-from-send: " + ex.getMessage() + " " + ex.getCause());
        }
    }


    public ListQueuesResult listQueues() {
        return amazonSQSAsync.listQueues();
    }
}
