### ISSUE TITLE
@MessageMapping Conflicting With WebSockets Implementation

### ISSUE THREAD

**Issue by sayan-chaliha** [spring-cloud/spring-cloud-aws#214]
Hey,

I use WebSockets in my Spring application and I wanted to integrate with Spring Cloud AWS Messaging to use SNS and SQS.

For my WebSockets I use @MessageMapping and it works great. However, the SQS listener is picking up all @MessageMapping annotated methods (regardless of what the class level annotation is) and assuming that it's an SQS queue and continually retrying to poll them.

Is there a quick fix, some configuration I could use, to make only @SqsListener annotated methods available for polling? I looked at the code -- so I know there's no class level filter annotation, and all @SqsListener and @MessageMapping annotated methods are being pulled in. Is there anyway this behaviour can be replaced with custom code?

Thanks!

**Comment by sayan-chaliha** [comment]
So, I've noticed that during boot a check is done in SQS to see if a queue by a given name exists. Even after the check fails, I continually keep getting these logs every 10 seconds for queues that do not exist:

[tomcat:launch] WARN  [org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer#0-2] 2017-04-18 15:47:53.189 SimpleMessageListenerContainer:271 - An Exception occurred while polling queue '/test'. The failing operation will be retried in 10000 milliseconds
[tomcat:launch] java.lang.NullPointerException
[tomcat:launch] 	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$AsynchronousMessageListener.run(SimpleMessageListenerContainer.java:255)
[tomcat:launch] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[tomcat:launch] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[tomcat:launch] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[tomcat:launch] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[tomcat:launch] 	at java.lang.Thread.run(Thread.java:745)
