### ISSUE TITLE
SQS listeners don't take class types into account when deserializing generic objects

### ISSUE THREAD

**Issue by jtcotton63** [spring-cloud/spring-cloud-aws#264]
Say I'm writing a REST controller method that receives a generic object:

````java
@RestController
@RequestMapping("/collection")
@PreAuthorize("hasAuthority('VOLLEYMETRICS_ADMIN')")
public class SystemEventsController {

	@RequestMapping(value = "", method = RequestMethod.POST)
	public void handleItemCreatedEvent(@RequestBody CreateEvent<Item> event) {
		// Notice this works just fine
		// I can manipulate the Item to my wishes
		Item item = event.getNewValue();
		// Do stuff with the new item
	}
}
````
where the CreateEvent<T> class is:

````java
public class CreateEvent<T> {
    private final T newValue;
    private final Instant changedAt;

    public CreateEvent(@JsonProperty("newValue") T newValue, @JsonProperty("changedAt") Instant changedAt) {
        this.newValue = newValue;
        this.changedAt = changedAt;
    }

	// Getters and setters not shown
````
and the Item class is:
````java
public class Item {
    private String aString;
    private int anInt;

    // Default constructor, getters, and setters not shown
}
````

The above example works just fine. Spring is able to infer the type of the generic from the signature of the controller method. This allows Jackson to deserialize the CreateEvent.newValue property into an object of type Item.

Now, let's do the same for an SQS-listening method:

````java
@Service
@Async
public class SQSListener {

	// Autowired constructor not shown

	@SqsListener(value = "${system.property.amazon.sqs.name}", deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS)
	public void handleItemCreatedEventViaSQS(@NotificationMessage CreateEvent<Item> event) {
        Item item = event.getNewValue();     // Exception thrown here
        // Never get to do stuff with the item
    }
}
````

This time, the an exception is thrown whenever calling event.getNewValue():

````java
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.company.Item
	at com.company.service.SQSListener.handleItemCreatedEventViaSQS(SQSListener.java:48) ~[main/:na]
	at com.company.service.SQSListener$$FastClassBySpringCGLIB$$817fccac.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at com.company.commons.async.AsyncThreadPoolExecutor.lambda$propagateSecurityContext$0(AsyncThreadPoolExecutor.java:40) ~[commons-2.4.3.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
````

It appears that Jackson didn't know what type to instantiate when it tried to deserialize the CreateEvent.newValue property, so it went with a map. This is weird, bc the Spring MVC controller methods are able to pass the type specified in the method signature to Jackson so that the generic is deserialized into the correct object, but SQS listening methods don't do that.

More relative info:
Using spring cloud starter version Brixton.RELEASE
Using spring cloud aws version 1.2.1.RELEASE

**Comment by maciejwalkowiak** [comment]
Adding `@NotificationMessage` to a parameter makes Spring Cloud AWS use another converter to deserialize message coming from SNS (check [documentation](http://cloud.spring.io/spring-cloud-static/spring-cloud-aws/2.0.0.RC2/single/spring-cloud-aws.html#_annotation_driven_http_notification_endpoint) for more details.

In your case, I believe you should be able to deserialize it properly with generic type if you remove this annotation. If not, #332 adds ability to set custom `ObjectMapper` to SQS listeners.

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.
