### ISSUE TITLE
Consider to upgrade to the latest Jackson

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-aws#285]
Since the current `master` is already based on the Spring Framework `5.0` and that one uses Jackson `2.9.3`: https://github.com/spring-projects/spring-framework/blob/master/build.gradle#L48, would be better to specify exactly this version for compatibility with SF.

Currently SC-AWS pulls Jackson transitively via `aws-java-sdk-core` and that one is `2.6.6` which isn't compatible with current SF:
```
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/InvalidDefinitionException
	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:74)
	at org.springframework.integration.http.converter.MultipartAwareFormHttpMessageConverter.<init>(MultipartAwareFormHttpMessageConverter.java:53)
	at org.springframework.integration.http.inbound.HttpRequestHandlingEndpointSupport.<init>(HttpRequestHandlingEndpointSupport.java:142)
	at org.springframework.integration.http.inbound.HttpRequestHandlingMessagingGateway.<init>(HttpRequestHandlingMessagingGateway.java:76)
	at org.springframework.integration.aws.inbound.SnsInboundChannelAdapter.<init>(SnsInboundChannelAdapter.java:88)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	... 43 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException
```

Right, I can override it the in SI-AWS, but you are going to suffer the same problem if don't override. 
And at the same time I won't need to hack it on my side since I will pull the proper Jackson from your 😄 .

Thanks.

**Comment by aemruli** [comment]
thansk for reporting @artembilan. I defined the dependency explicitly, even thought he latest AWS SDK updated theirs we should manage the version on ourselves.
