### ISSUE TITLE
Outdated dependency to spring-cloud-context

### ISSUE THREAD

**Issue by mziemba** [spring-cloud/spring-cloud-aws#346]
Hey!

https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-dependencies/pom.xml points to spring-cloud-context 1.3.2.RELEASE, which is incompatible with Spring Boot 2.0.x.

When running an application using Spring Boot 2.0.3 and spring-cloud-aws 2.0.0.RELEASE, I get:

```
15:43:43.197 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:161)                                                                                                            at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:102)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:68)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:358)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
```

**Comment by antinodes** [comment]
Is there a known workaround for this problem until the PR is merged and released?

**Comment by mziemba** [comment]
You have to add `"org.springframework.cloud:spring-cloud-context:2.0.0.RELEASE"` explicitly to your dependencies, not to use the version defined in spring-cloud-aws BOM. In our case, we have set the version of spring-cloud-context in our BOM that we use across our services, something like this:

```
dependencyManagement {
    val springBootVersion = "2.0.3.RELEASE"
    val springCloudVersion = "Finchley.RELEASE"
    val springCloudAwsVersion = "2.0.0.RELEASE"

    imports {
        mavenBom("org.springframework.boot:spring-boot-dependencies:$springBootVersion")
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion")
        mavenBom("org.springframework.cloud:spring-cloud-aws-dependencies:$springCloudAwsVersion")
    }

    dependencies {
        // FIXME: this is to mitigate https://github.com/spring-cloud/spring-cloud-aws/issues/346
        dependency("org.springframework.cloud:spring-cloud-context:2.0.0.RELEASE")

        ...other dependency versions...
    }
}
```

**Comment by maciejwalkowiak** [comment]
This issue is not present anymore when using `2.2.1` version.
