### ISSUE TITLE
TaskExecutor is not set for ResourceLoader with autoconfiguration

### ISSUE THREAD

**Issue by gschukin** [spring-cloud/spring-cloud-aws#40]
When I tried to upload a file to S3 with resource loader I received an exception
```
Caused by: java.lang.IllegalArgumentException: TaskExecutor must not be null
	at org.springframework.util.Assert.notNull(Assert.java:112)
	at org.springframework.core.task.support.ExecutorServiceAdapter.<init>(ExecutorServiceAdapter.java:55)
	at org.springframework.cloud.aws.core.io.s3.SimpleStorageResource$SimpleStorageOutputStream.<init>(SimpleStorageResource.java:167)
	at org.springframework.cloud.aws.core.io.s3.SimpleStorageResource.getOutputStream(SimpleStorageResource.java:132)
	at org.springframework.core.io.WritableResource$getOutputStream.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at ru.ptsecurity.cloudmanagement.carunner.Application.run(Application.groovy:89)
	at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:677)
	... 9 more
```
Sample code
``` groovy
@Slf4j
@Configuration
@EnableAutoConfiguration(exclude = [
        AmazonRdsDatabaseRegistrar.class,
        MessagingAutoConfiguration.class,
        ElastiCacheAutoConfiguration.class,
        MailSenderAutoConfiguration.class])
@ComponentScan
@EnableAsync
public class Application implements CommandLineRunner {
    public static void main(String[] args) {
        def context = SpringApplication.run(Application.class, args)
    }

    @Autowired
    private ResourceLoader resourceLoader

    @Override
    void run(String... args) throws Exception {
        Resource resource = resourceLoader.getResource('s3://testbucket/test.txt')
        WritableResource writableResource = (WritableResource) resource
        OutputStream outputStream = writableResource.getOutputStream()
        outputStream.write('test'.getBytes())
        outputStream.close()
    }
}

@CompileStatic
@Configuration
@EnableAsync(proxyTargetClass = true)
class SchedulingAndAsyncConfiguration implements AsyncConfigurer {

    @Bean
    @Override
    Executor getAsyncExecutor() {
        def executor = new ThreadPoolTaskExecutor()
        executor.corePoolSize = 4
        executor.maxPoolSize = 32
        executor.queueCapacity = 2048
        executor.waitForTasksToCompleteOnShutdown = true
        executor.awaitTerminationSeconds = 60
        executor.threadNamePrefix = 'asyncThreadPoolTaskExecutor-'

        executor
    }

    @Bean
    @Override
    AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {
        new SimpleAsyncUncaughtExceptionHandler()
    }
}
```

It will be nice if ResourceLoaderConfigureAdapter will be added in order to fine tune ResourceLoader, eg specify custom TaskExecutor.

**Comment by aemruli** [comment]
Hello @gschukin thanks for spotting. 
I have fixed the broken task executor within 91365f4. 
I will add support for a task executor configuration in the next day, therefore I will leave this ticket open.
