### ISSUE TITLE
Unable to receive SQS messages when "id" header is not a UUID

### ISSUE THREAD

**Issue by sdavids13** [spring-cloud/spring-cloud-aws#420]
Spring cloud version: Greenwich

An upstream provider is sending SQS message attribute headers one of which is an "id" header that is not a UUID, we are unable to receive those messages due to the following exception:

```
Exception in thread "simpleMessageListenerContainer-75" java.lang.IllegalArgumentException: Invalid UUID string: foo
	at java.util.UUID.fromString(UUID.java:194)
	at org.springframework.cloud.aws.messaging.core.QueueMessageUtils.getMessageAttributesAsMessageHeaders(QueueMessageUtils.java:76)
	at org.springframework.cloud.aws.messaging.core.QueueMessageUtils.createMessage(QueueMessageUtils.java:56)
```

We would like to have Spring provide a best-effort conversion but fall back to using a plain string or provide a mechanism to turn off the conversion.

**Comment by kgreenman-r7** [comment]
I am having the same issue, is there a reason this is forcing this attribute to be a uuid? I've had to write my own message converter in order to get around this issue

**Comment by maciejwalkowiak** [comment]
"id" header has UUID type because of how Spring Messaging works. I am thinking if we could map "id" header from SQS message to another name, perhaps "sqs-id".

**Comment by mkatircioglu** [comment]
@maciejwalkowiak Why don't we just remove forcing UUID conversion in QueueMessageUtils?

https://github.com/spring-cloud/spring-cloud-aws/blob/ddde60b44bc09d155ce926c5d366f45008752d30/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/QueueMessageUtils.java#L89-L92

Since while using QueueMessagingTemplate on publisher side, it is guaranteed to be UUID however it may not be on subscriber side if publisher is different. It might be better to accept as it comes.

**Comment by voytech** [comment]
MessageHeaders.getId already expects UUID so removing forced conversion seems hard. There is already SqsMessageHeaders class with some sqs specific headers support ( convenient getters ). Maybe adding support via sqs-id header (and getter getSqsId()) ? And Internal ‚id’ header  generated Internally at instantiation time when it is not UUID ?
