### ISSUE TITLE
BeanCreationException when using context-resource-loader

### ISSUE THREAD

**Issue by noomkram** [spring-cloud/spring-cloud-aws#53]
I’m encountering the exception below when trying to use the ```<context-resource-loader />``` in my application.  I’ve narrowed it down to the following line of code in [ResourceLoaderBeanPostProcessor](
https://github.com/spring-cloud/spring-cloud-aws/blob/1.0.0.M2/spring-cloud-aws-context/src/main/java/org/springframework/cloud/aws/context/support/io/ResourceLoaderBeanPostProcessor.java#L91):

```beanFactory.registerResolvableDependency(BeanFactory.class, this.applicationContext);```

When I comment this line out, the application deploys successfully and I’m able to leverage the ```SimpleStorageResourceLoader``` injected via:

```
@Inject
private ResourceLoader resourceLoader;
```

I’m not going to pretend to fully understand what is going on but it seems like any BeanPostProcessor that gets applied after the ResourceLoaderBeanPostProcessor fails.  I’m working on putting a smaller test case together to demonstrate the issue but wanted to log the ticket in case anyone has encountered it.

Spring Cloud AWS config:
```
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:aws-context="http://www.springframework.org/schema/cloud/aws/context"
  xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/cloud/aws/context
        http://www.springframework.org/schema/cloud/aws/context/spring-cloud-aws-context-1.0.xsd">

  <aws-context:context-region region="us-west-2" />
  <aws-context:context-credentials />
  <aws-context:context-resource-loader />
</beans>
```

Relevant Spring dependencies:
```
    <spring.version>4.1.4.RELEASE</spring.version>
    <spring-cloud-aws-context.version>1.0.0.RC2</spring-cloud-aws-context.version>
    <spring-data-commons.version>1.9.2.RELEASE</spring-data-commons.version>
    <spring-data-jpa.version>1.7.2.RELEASE</spring-data-jpa.version>
    <spring-integration.version>4.1.2.RELEASE</spring-integration.version>
    <spring-mobile-device.version>1.1.3.RELEASE</spring-mobile-device.version>
    <spring-security.version>3.2.5.RELEASE</spring-security.version>
```

Exception (happens on start up):
```
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.integration.expression.IntegrationEvaluationContextAwareBeanPostProcessor#0': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration.setObjectPostProcessor(org.springframework.security.config.annotation.ObjectPostProcessor); nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'objectPostProcessor' defined in class org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.springframework.beans.factory.config.AutowireCapableBeanFactory]: : No qualifying bean of type [org.springframework.beans.factory.config.AutowireCapableBeanFactory] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.beans.factory.config.AutowireCapableBeanFactory] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:472) ~[AbstractAutowireCapableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[AbstractBeanFactory$1.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[DefaultSingletonBeanRegistry.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[AbstractBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[AbstractBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:232) ~[PostProcessorRegistrationDelegate.class:4.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:615) ~[AbstractApplicationContext.class:4.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:465) ~[AbstractApplicationContext.class:4.1.4.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403) ~[ContextLoader.class:4.1.4.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) ~[ContextLoader.class:4.1.4.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [ContextLoaderListener.class:4.1.4.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4795) [catalina.jar:8.0.14]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5221) [catalina.jar:8.0.14]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.14]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724) [catalina.jar:8.0.14]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700) [catalina.jar:8.0.14]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.14]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:919) [catalina.jar:8.0.14]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:461) [catalina.jar:8.0.14]
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1495) [catalina.jar:8.0.14]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300) [tomcat-coyote.jar:8.0.14]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [na:1.8.0_20]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:1.8.0_20]
	at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1432) [catalina.jar:8.0.14]
	at org.apache.catalina.manager.ManagerServlet.deploy(ManagerServlet.java:711) [catalina.jar:8.0.14]
	at org.apache.catalina.manager.ManagerServlet.doPut(ManagerServlet.java:423) [catalina.jar:8.0.14]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647) [servlet-api.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.14]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.14]
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108) [catalina.jar:8.0.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.14]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.14]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.14]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.14]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:618) [catalina.jar:8.0.14]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.14]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.14]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.14]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.14]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) [catalina.jar:8.0.14]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081) [tomcat-coyote.jar:8.0.14]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) [tomcat-coyote.jar:8.0.14]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) [tomcat-coyote.jar:8.0.14]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566) [tomcat-coyote.jar:8.0.14]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523) [tomcat-coyote.jar:8.0.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.14]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
```

**Comment by aemruli** [comment]
Hello @noomkram thanks for reporting. As far as I am aware nobody else had this issue. Would be great if you can provide a test case so that we can fix. 

The mentionend line is basically there to allow the use of the resource loader if you inject yourself an application context or a bean factory.

**Comment by noomkram** [comment]
Attached is a web project when deployed will generate the noted exception.  

If I remove WebSecurityConfig.java from the array of root config classes, the error goes away.
  @Override
  protected Class<?>[] getRootConfigClasses() {
    return new Class<?>[] { ApplicationConfiguration.class, WebSecurityConfig.class };
  }
 

     On Thursday, February 12, 2015 7:08 AM, Agim Emruli <notifications@github.com> wrote:
   

 Hello @noomkram thanks for reporting. As far as I am aware nobody else had this issue. Would be great if you can provide a test case so that we can fix. The mentionend line is basically there to allow the use of the resource loader if you inject yourself an application context or a bean factory.—

**Comment by noomkram** [comment]
My apologies, [the file](https://drive.google.com/file/d/0BwkeV2jMl-0vX2Z0YlVObHp0dVU/view?usp=sharing)

**Comment by aemruli** [comment]
Thanks will try to reproduce and fix that with rc3

**Comment by aemruli** [comment]
@noomkram thanks for poviding your sample. With the fixes I did in the linked commit I am not receiving this error any more. Your app starts but fails due to a missing authentication manager in Spring Security. 

RC3 should be available in just a few hours, would be great if you can test that.

**Comment by noomkram** [comment]
Tested and working with no issues.  Thank you.
