### ISSUE TITLE
Cannot run application locally due to SdkClientException

### ISSUE THREAD

**Issue by rmpestano** [spring-cloud/spring-cloud-aws#532]
**Describe the bug**

Since version `1.11.678` of aws java sdk the sdk is throwing a ` SdkClientException` when it cannot connect to aws services, [see here](https://github.com/aws/aws-sdk-java/blob/06a2180efe02da1a0b6efcc693efc8e2de355eb7/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java#L394).

In `AwsCloudEnvironmentCheckUtils` we are expecting a `AmazonClientException`, [see here](https://github.com/spring-cloud/spring-cloud-aws/blob/33e1535012dba06573e29df74d8ba4f1419e3e5c/spring-cloud-aws-context/src/main/java/org/springframework/cloud/aws/context/support/env/AwsCloudEnvironmentCheckUtils.java#L40).

So when I run the application locally I got the following exception, using aws-java-sdk 1.11.678 or greater:

```
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100) ~[aws-java-sdk-core-1.11.698.jar:na]
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70) ~[aws-java-sdk-core-1.11.698.jar:na]
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75) ~[aws-java-sdk-core-1.11.698.jar:na]
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:62) ~[aws-java-sdk-core-1.11.698.jar:na]
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:400) ~[aws-java-sdk-core-1.11.698.jar:na]
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:369) ~[aws-java-sdk-core-1.11.698.jar:na]
	at org.springframework.cloud.aws.context.support.env.AwsCloudEnvironmentCheckUtils.isRunningOnCloudEnvironment(AwsCloudEnvironmentCheckUtils.java:38) ~[spring-cloud-aws-context-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cloud.aws.context.annotation.OnAwsCloudEnvironmentCondition.matches(OnAwsCloudEnvironmentCondition.java:37) ~[spring-cloud-aws-context-2.1.4.RELEASE.jar:2.1.4.RELEASE]

```

I'm using spring boot 2.1.13.RELEASE

**Comment by rmpestano** [comment]
Guys, nevermind it is just a warn message (with stacktrack), I'll close this, sorry for that.
```   
} catch (AmazonClientException ace) {
            log.warn("Unable to retrieve the requested metadata (" + path + "). " + ace.getMessage(), ace);
            return null;
        } 
```
