### ISSUE TITLE
bug(dep): org.springframework.http missing when using QueueMessageTemplate

### ISSUE THREAD

**Issue by jef** [spring-cloud/spring-cloud-aws#540]
**Describe the bug**

Starting a new project with initializer doesn't work with `QueueMessageTemplate` as `org.springframework.http.converter.json.Jackson2ObjectMapperBuilder` is missing.

![image](https://user-images.githubusercontent.com/12074633/78805653-ac867a80-798f-11ea-9167-f1ab0990f747.png)

**Sample**

`DemoApplication.kt`

```kotlin
package com.example.demo

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import com.amazonaws.client.builder.AwsClientBuilder
import com.amazonaws.services.sqs.AmazonSQSAsync
import com.amazonaws.services.sqs.AmazonSQSAsyncClientBuilder
import org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration

@SpringBootApplication
class DemoApplication

fun main(args: Array<String>) {
	runApplication<DemoApplication>(*args)
}

@Configuration
class AwsConfig {
    @Bean
    fun workerPayloadTemplate(amazonSqs: AmazonSQSAsync) = QueueMessagingTemplate(amazonSqs)

    @Bean
    fun amazonSqs(): AmazonSQSAsync = AmazonSQSAsyncClientBuilder.standard()
            .withEndpointConfiguration(AwsClientBuilder.EndpointConfiguration("http://localhost:4576", "us-east-1")).build()
}
```

STDOUT:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.6.RELEASE)

2020-04-08 11:52:21.296  WARN 75332 --- [           main] o.s.boot.StartupInfoLogger               : InetAddress.getLocalHost().getHostName() took 1031 milliseconds to respond. Please verify your network configuration (macOS machines may need to add entries to /etc/hosts).
2020-04-08 11:52:21.304  INFO 75332 --- [           main] com.example.demo.DemoApplicationKt       : Starting DemoApplicationKt on GLXC02YM9GRLVCG with PID 75332 (/private/tmp/demo/build/classes/kotlin/main started by jef.lecompte in /private/tmp/demo)
2020-04-08 11:52:21.304  INFO 75332 --- [           main] com.example.demo.DemoApplicationKt       : The following profiles are active: KRONA
2020-04-08 11:52:28.430  WARN 75332 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'workerPayloadTemplate' defined in class path resource [com/example/demo/AwsConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate]: Factory method 'workerPayloadTemplate' threw exception; nested exception is java.lang.NoClassDefFoundError: org.springframework.http.converter.json.Jackson2ObjectMapperBuilder
2020-04-08 11:52:28.441  INFO 75332 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-08 11:52:28.452 ERROR 75332 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'workerPayloadTemplate' defined in class path resource [com/example/demo/AwsConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate]: Factory method 'workerPayloadTemplate' threw exception; nested exception is java.lang.NoClassDefFoundError: org.springframework.http.converter.json.Jackson2ObjectMapperBuilder
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$217/0000000000000000.getObject(Unknown Source) ~[na:na]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
        at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:29) ~[main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate]: Factory method 'workerPayloadTemplate' threw exception; nested exception is java.lang.NoClassDefFoundError: org.springframework.http.converter.json.Jackson2ObjectMapperBuilder
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        ... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org.springframework.http.converter.json.Jackson2ObjectMapperBuilder
        at org.springframework.cloud.aws.messaging.core.support.AbstractMessageChannelMessagingSendingTemplate.initMessageConverter(AbstractMessageChannelMessagingSendingTemplate.java:126) ~[spring-cloud-aws-messaging-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate.<init>(QueueMessagingTemplate.java:96) ~[spring-cloud-aws-messaging-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate.<init>(QueueMessagingTemplate.java:74) ~[spring-cloud-aws-messaging-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate.<init>(QueueMessagingTemplate.java:54) ~[spring-cloud-aws-messaging-2.2.1.RELEASE.jar:2.2.1.RELEASE]
        at com.example.demo.AwsConfig.workerPayloadTemplate(DemoApplication.kt:22) ~[main/:na]
        at com.example.demo.AwsConfig$$EnhancerBySpringCGLIB$$e29cee4a.CGLIB$workerPayloadTemplate$0(<generated>) ~[main/:na]
        at com.example.demo.AwsConfig$$EnhancerBySpringCGLIB$$e29cee4a$$FastClassBySpringCGLIB$$2723dad8.invoke(<generated>) ~[main/:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at com.example.demo.AwsConfig$$EnhancerBySpringCGLIB$$e29cee4a.workerPayloadTemplate(<generated>) ~[main/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        ... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.http.converter.json.Jackson2ObjectMapperBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1078) ~[na:na]
        ... 35 common frames omitted
```

**Comment by maciejwalkowiak** [comment]
Thanks for reporting. We will fix it by either injecting existing `ObjectMapper` or creating one without using builder from `org.springframework.http` package.

**Comment by jef** [comment]
nice! thanks,

**Comment by maciejwalkowiak** [comment]
Using ObjectMapper provided by Spring Boot was high on my personal wishlist ;)
